#!/usr/bin/env node

const { getPackages, run } = require('./utils')

require('exec-promise')(([command, ...args]) =>
  getPackages().forEach(({ dir, name }) => {
    console.log('*', name)
    return run(command, args, { cwd: dir })
  })
)
